/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsPluginAdapter {
  onResolve?: (arg: string) => any
  onLoad?: (arg: string) => any
}
export declare function build(context: string, entry: string, plugins: Array<JsPluginAdapter>): Promise<void>
